# Informations de connexion à la base de données
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
# Change 'root' et le mot de passe vide par tes propres identifiants MySQL si nécessaire
hibernate.connection.url=jdbc:mysql://localhost:3306/etat_civil?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
hibernate.connection.username=root
hibernate.connection.password=

# Configuration Hibernate
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true